### ISSUE TITLE
关于SICP书籍封面的抠图

### ISSUE THREAD

**Issue by DeathKing** [joseph-zhang/SICP-Learning#1]
我之前让朋友帮忙抠了一个，感觉比你Repo里面的那个质量要好（就是Lambda那个部分，黑边保留得比较好）。需要的话可自取：

![sicp](https://user-images.githubusercontent.com/895809/30737441-42c69d12-9fb9-11e7-9c63-69e9aa4cbbd9.png)

另外还有几个其它风格的Cover，兴许你有用得上的：

![part-of-sicp-cover](https://user-images.githubusercontent.com/895809/30737493-7047586c-9fb9-11e7-849b-edecac7b27cc.jpg)
![sicp_1st_cover](https://user-images.githubusercontent.com/895809/30737504-77134b42-9fb9-11e7-811e-27e713c30e61.jpg)
![sicp](https://user-images.githubusercontent.com/895809/30737500-73c66780-9fb9-11e7-83a4-20a0ec4c3daa.jpg)

事实上……我还有一个SICP内部版的封面，不过这个网上应该找得到，就不发了。

**Comment by joseph-zhang** [comment]
Thanks a lot : )
非常感谢您给的这些图，我一直很喜欢这个封面
最近也开始关注您的翻译项目了，希望能从中学到更多~
